// <auto-generated />
namespace ChatLoco.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201704061935117_user_roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
